name: linux-build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install \
          cmake make g++ \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-ttf-dev \
          libsqlite3-dev \
          libssl-dev \
          libcurl4-openssl-dev \
          libavcodec-dev \
          libavdevice-dev \
          libavfilter-dev \
          libavformat-dev \
          libavutil-dev \
          libswresample-dev \
          libswscale-dev \
      - name: Build
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug
          cmake --build ${{github.workspace}}/build --config Debug
